In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\python\guvi_pro\EMI prediction\data\emi_prediction_dataset.csv")

C:\Users\HP\AppData\Local\Temp\ipykernel_17980\1393772715.py:1: DtypeWarning: Columns (0: age) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\python\guvi_pro\EMI prediction\data\emi_prediction_dataset.csv")

In [3]:
df.head()
df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 404800 entries, 0 to 404799
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   age                     404800 non-null  object
 1   gender                  404800 non-null  str
 2   marital_status          404800 non-null  str
 3   education               402396 non-null  str
 4   monthly_salary          404800 non-null  str
 5   employment_type         404800 non-null  str
 6   years_of_employment     404800 non-null  float64
 7   company_type            404800 non-null  str
 8   house_type              404800 non-null  str
 9   monthly_rent            402374 non-null  float64
 10  family_size             404800 non-null  int64
 11  dependents              404800 non-null  int64
 12  school_fees             404800 non-null  float64
 13  college_fees            404800 non-null  float64
 14  travel_expenses         404800 non-null  float64
 15  groceries_utilities     404800 non-null  float64
 16  other_monthly_expenses  404800 non-null  float64
 17  existing_loans          404800 non-null  str
 18  current_emi_amount      404800 non-null  float64
 19  credit_score            402380 non-null  float64
 20  bank_balance            402374 non-null  str
 21  emergency_fund          402449 non-null  float64
 22  emi_scenario            404800 non-null  str
 23  requested_amount        404800 non-null  float64
 24  requested_tenure        404800 non-null  int64
 25  emi_eligibility         404800 non-null  str
 26  max_monthly_emi         404800 non-null  float64
dtypes: float64(12), int64(3), object(1), str(11)
memory usage: 117.3+ MB

In [4]:
print(df['age'].head())
print(df['monthly_salary'].head())
print(df['bank_balance'].head())

0    38.0
1    38.0
2    38.0
3    58.0
4    48.0
Name: age, dtype: object
0    82600.0
1    21500.0
2    86100.0
3    66800.0
4    57300.0
Name: monthly_salary, dtype: str
0    303200.0
1     92500.0
2    672100.0
3    440900.0
4     97300.0
Name: bank_balance, dtype: str

In [5]:
df.isnull().sum()

age                          0
gender                       0
marital_status               0
education                 2404
monthly_salary               0
employment_type              0
years_of_employment          0
company_type                 0
house_type                   0
monthly_rent              2426
family_size                  0
dependents                   0
school_fees                  0
college_fees                 0
travel_expenses              0
groceries_utilities          0
other_monthly_expenses       0
existing_loans               0
current_emi_amount           0
credit_score              2420
bank_balance              2426
emergency_fund            2351
emi_scenario                 0
requested_amount             0
requested_tenure             0
emi_eligibility              0
max_monthly_emi              0
dtype: int64

In [6]:
#Clean Numeric Columns
df['age'] = pd.to_numeric(df['age'], errors='coerce')

df['monthly_salary'] = pd.to_numeric(
    df['monthly_salary'],
    errors='coerce'
)

df['bank_balance'] = pd.to_numeric(
    df['bank_balance'],
    errors='coerce'
)

In [7]:
#Missing Value Report

missing = df.isnull().sum()

missing_percent = (
    missing / len(df)
) * 100

pd.DataFrame({
    'Missing_Count': missing,
    'Missing_Percent': missing_percent
}).sort_values(
    'Missing_Count',
    ascending=False
)

                        Missing_Count  Missing_Percent
bank_balance                     4392         1.084980
monthly_rent                     2426         0.599308
credit_score                     2420         0.597826
education                        2404         0.593874
emergency_fund                   2351         0.580781
monthly_salary                   1993         0.492342
age                                 3         0.000741
years_of_employment                 0         0.000000
gender                              0         0.000000
marital_status                      0         0.000000
employment_type                     0         0.000000
family_size                         0         0.000000
house_type                          0         0.000000
company_type                        0         0.000000
dependents                          0         0.000000
groceries_utilities                 0         0.000000
school_fees                         0         0.000000
college_fees                        0         0.000000
travel_expenses                     0         0.000000
current_emi_amount                  0         0.000000
existing_loans                      0         0.000000
other_monthly_expenses              0         0.000000
emi_scenario                        0         0.000000
requested_amount                    0         0.000000
requested_tenure                    0         0.000000
emi_eligibility                     0         0.000000
max_monthly_emi                     0         0.000000

In [8]:
#fill categorical column
df['education'] = df['education'].fillna(
    df['education'].mode()[0]
)

In [9]:
#fill numerical column
num_cols = [
    'monthly_rent',
    'credit_score',
    'bank_balance',
    'emergency_fund',
    'monthly_salary',
    'age'
]

for col in num_cols:
    df[col] = df[col].fillna(
        df[col].median()
    )

In [10]:
df.isnull().sum().sum()

np.int64(0)

In [11]:
#Check Duplicates
df.duplicated().sum()

np.int64(0)

In [12]:
df[['age',
    'monthly_salary',
    'credit_score',
    'bank_balance',
    'requested_amount',
    'max_monthly_emi']].describe()

,age,monthly_salary,credit_score,bank_balance,requested_amount,max_monthly_emi
count,404800.000000,404800.000000,404800.000000,4.048000e+05,4.048000e+05,404800.000000
mean,38.875825,59470.891843,700.857083,2.411676e+05,3.708554e+05,6763.602156
std,9.303538,43284.807915,88.170806,1.822615e+05,3.451945e+05,7741.263317
min,26.000000,3967.000000,0.000000,6.100000e+03,1.000000e+04,500.000000
25%,32.000000,35400.000000,654.000000,1.053000e+05,1.240000e+05,500.000000
50%,38.000000,51700.000000,701.000000,1.959000e+05,2.360000e+05,4211.200000
75%,48.000000,72800.000000,748.000000,3.292000e+05,4.940000e+05,9792.000000
max,59.000000,499970.000000,1200.000000,1.717300e+06,1.500000e+06,91040.400000

In [13]:
df.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,...,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38.0,Female,Married,Professional,82600.0,Private,0.9,Mid-size,Rented,20000.0,...,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38.0,Female,Married,Graduate,21500.0,Private,7.0,MNC,Family,0.0,...,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38.0,Male,Married,Professional,86100.0,Private,5.8,Startup,Own,0.0,...,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0
3,58.0,Female,Married,High School,66800.0,Private,2.2,Mid-size,Own,0.0,...,No,0.0,685.0,440900.0,178100.0,Vehicle EMI,304000.0,83,Eligible,16170.0
4,48.0,Female,Married,Professional,57300.0,Private,3.4,Mid-size,Family,0.0,...,No,0.0,770.0,97300.0,28200.0,Home Appliances EMI,252000.0,7,Not_Eligible,500.0

In [14]:
#Perform Final Data Validation
print("Duplicates:", df.duplicated().sum())

print("Age < 25:", (df['age'] < 25).sum())
print("Age > 60:", (df['age'] > 60).sum())

print("Credit < 300:", (df['credit_score'] < 300).sum())
print("Credit > 850:", (df['credit_score'] > 850).sum())

print("Salary < 15000:", (df['monthly_salary'] < 15000).sum())
print("Salary > 200000:", (df['monthly_salary'] > 200000).sum())

Duplicates: 0
Age < 25: 0
Age > 60: 0
Credit < 300: 1566
Credit > 850: 3210
Salary < 15000: 6417
Salary > 200000: 3605

In [15]:
df = df[
    (df['credit_score'] >= 300) &
    (df['credit_score'] <= 850)
]

df = df[
    (df['monthly_salary'] >= 15000) &
    (df['monthly_salary'] <= 200000)
]

In [16]:
print(df.shape)

(390099, 27)

In [17]:
df.to_csv(r"C:\Users\HP\OneDrive\Desktop\python\guvi_pro\EMI prediction\data\EMI_dataset_cleaned.csv", index=False)